sonar.projectKey=Task-Manager
sonar.projectName=Task Manager Project
sonar.projectVersion=1.0

# Hem backend hem frontend klasörlerini dahil ediyoruz
sonar.sources=backend, frontend

# Sadece kendi yazdığınız kodları analiz etmek için gereksizleri dışlıyoruz 
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/.next/**

sonar.sourceEncoding=UTF-8